language: go
go:
  - "1.13"
  - tip
env:
  global:
    - MONGODB=4.2.1
install: true
before_script:
  - sudo apt-get install graphviz
  - wget http://fastdl.mongodb.org/linux/mongodb-linux-x86_64-ubuntu1604-${MONGODB}.tgz -O /tmp/mongodb.tgz
  - tar -xvf /tmp/mongodb.tgz
  - mkdir /tmp/data
  - ${PWD}/mongodb-linux-x86_64-ubuntu1604-${MONGODB}/bin/mongod --replSet rs0 --dbpath /tmp/data --logpath /tmp/mongodb.log --bind_ip 0.0.0.0 --fork
  - sleep 10
  - ${PWD}/mongodb-linux-x86_64-ubuntu1604-${MONGODB}/bin/mongo --eval 'rs.initiate()'
  - sleep 10
script:
  - go get github.com/modocache/gover
  - go get github.com/mattn/goveralls
  - go get golang.org/x/tools/cmd/cover
  - env GO111MODULE=on go test -coverprofile=fire.coverprofile
  - env GO111MODULE=on go test -coverprofile=auth.coverprofile ./ash
  - env GO111MODULE=on go test -coverprofile=axe.coverprofile ./axe
  - env GO111MODULE=on go test -coverprofile=blaze.coverprofile ./blaze
  - env GO111MODULE=on go test -coverprofile=coal.coverprofile ./coal
  - env GO111MODULE=on go test -coverprofile=example.coverprofile ./example
  - env GO111MODULE=on go test -coverprofile=flame.coverprofile ./flame
  - env GO111MODULE=on go test -coverprofile=glut.coverprofile ./glut
  - env GO111MODULE=on go test -coverprofile=heat.coverprofile ./heat
  - env GO111MODULE=on go test -coverprofile=spark.coverprofile ./spark
  - $HOME/gopath/bin/gover
  - $HOME/gopath/bin/goveralls -coverprofile=gover.coverprofile -service=travis-ci
after_script:
  - pkill mongod
  - cat /tmp/mongodb.log
matrix:
  allow_failures:
    - go: tip
