language: go
go:
  - '1.12'
  - tip
env:
  global:
    - MONGODB=4.0.6
install: true
before_script:
  - wget http://fastdl.mongodb.org/linux/mongodb-linux-x86_64-${MONGODB}.tgz -O /tmp/mongodb.tgz
  - tar -xvf /tmp/mongodb.tgz
  - mkdir /tmp/data
  - ${PWD}/mongodb-linux-x86_64-${MONGODB}/bin/mongod --replSet rs0 --dbpath /tmp/data --logpath /tmp/mongodb.log --bind_ip 0.0.0.0 --fork
  - sleep 10
  - ${PWD}/mongodb-linux-x86_64-${MONGODB}/bin/mongo --eval 'rs.initiate()'
  - sleep 10
script:
  - go get github.com/modocache/gover
  - go get github.com/mattn/goveralls
  - go get golang.org/x/tools/cmd/cover
  - make setup
  - env GO111MODULE=on go test -coverprofile=fire.coverprofile
  - env GO111MODULE=on go test -coverprofile=auth.coverprofile ./ash
  - env GO111MODULE=on go test -coverprofile=auth.coverprofile ./axe
  - env GO111MODULE=on go test -coverprofile=tools.coverprofile ./coal
  - env GO111MODULE=on go test -coverprofile=auth.coverprofile ./example
  - env GO111MODULE=on go test -coverprofile=tools.coverprofile ./flame
  - env GO111MODULE=on go test -coverprofile=auth.coverprofile ./glut
  - env GO111MODULE=on go test -coverprofile=auth.coverprofile ./spark
  - $HOME/gopath/bin/gover
  - $HOME/gopath/bin/goveralls -coverprofile=gover.coverprofile -service=travis-ci
after_script:
  - pkill mongod
  - cat /tmp/mongodb.log
matrix:
  allow_failures:
    - go: tip
