source 'https://rubygems.org'

ruby '2.4.2'

gem 'middleman', '>= 4.0.0'
gem 'middleman-autoprefixer'
gem 'middleman-livereload'
gem 'middleman-sprockets'
gem 'middleman-syntax'
gem 'mime-types'
gem 'redcarpet'
gem 'sass'
gem 'slim'
